modalka_1.0
js-tasks-ru/htmlcss-20230411_pavlov-aleksandr pull request #10
Opened 2023-05-12 19:44 UTC by mcAlexon

2023-05-12 19:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-16 06:34 UTC, GSemikozov requested changes

2023-05-16 06:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.overflow{
.modal?
фон - через rgba.
position - absolute.

2023-05-16 06:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal{
.modal__window

2023-05-16 06:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +width: 428px;
max-width

2023-05-16 06:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +height: 294px;
удалим

2023-05-16 06:34 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-close{
.modal__close

2023-05-16 14:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-16 15:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-16 15:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-16 16:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-17 15:43 UTC, GSemikozov requested changes

2023-05-17 15:43 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal{
не исправлено

2023-05-19 14:57 UTC, GSemikozov requested changes

2023-05-19 14:57 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.page{
1. это .modal
2. fixed
3. не забываем про top / left
4. не забываем про полупрозрачный фон через rgba

2023-05-19 14:57 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: -80px;
не высоко ли?)

2023-05-24 12:10 UTC, GSemikozov requested changes

2023-05-24 12:10 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +        <button id="modal-open">Open modal</button>
нкопка открытия модалки - не часть модалки, ее надо вынести наружу (относительно компонента)

2023-05-24 12:10 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +left: 30%;
`left: 50%; transform: translate(-50%, -50%)`

2023-05-24 12:10 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +border: 1px solid black;
цвет бордера точно именно такой?

2023-05-25 09:47 UTC, GSemikozov approved these changes

2023-05-25 09:47 UTC, merged