bg_img_1.0
js-tasks-ru/htmlcss-20230411_pavlov-aleksandr pull request #13
Opened 2023-05-17 17:15 UTC by mcAlexon

2023-05-19 14:59 UTC, GSemikozov requested changes

2023-05-19 14:59 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +    background-image: url(/public/forest_2560.jpg);
это для десктопа, окей. Но - задача сделать картинку адаптивной в том смысле что под каждый брейкпоинт через медиа-запросы ставить картинку меньше/больше, в зависимости от выбранного подхода)

2023-05-19 18:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-19 18:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-19 18:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-19 18:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-19 18:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-26 21:15 UTC, GSemikozov approved these changes

2023-05-26 21:15 UTC, merged