burger__test_1.0
js-tasks-ru/htmlcss-20230411_pavlov-aleksandr pull request #19
Opened 2023-06-06 17:46 UTC by mcAlexon

2023-06-06 20:30 UTC, GSemikozov requested changes

2023-06-06 20:30 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    max-width: 375px;
лишнее ограничение, растягиваемся на весь вьюпорт, а ограничивать нужно уже вложенный элемент

2023-06-06 20:30 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    gap: 25%;
лучше в пикселях

2023-06-06 20:30 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +            <svg class="burger__close_icon" id="burger-menu-close" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
просто burger__close (речь ведь об элементе, а не о модификаторе который при этом используется без того ЧТО он должен модифицировать)

2023-06-06 20:30 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +            <svg class="burger__line" width="343" height="1" viewBox="0 0 343 1" fill="none" xmlns="http://www.w3.org/2000/svg">
линию можно отрисовать через css

2023-06-07 09:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-08 10:49 UTC, mcAlexon commented on 09-lection7/01-burger-menu/burger-menu.css
> +    gap: 25%;
сделал в пикселях

2023-06-08 10:49 UTC, mcAlexon commented on 09-lection7/01-burger-menu/index.html
> +            <svg class="burger__close_icon" id="burger-menu-close" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
изменил

2023-06-08 10:49 UTC, mcAlexon commented on 09-lection7/01-burger-menu/index.html
> +            <svg class="burger__icons" width="110" height="32" viewBox="0 0 110 32" fill="none" xmlns="http://www.w3.org/2000/svg">
изменил на burger__logo

2023-06-08 10:49 UTC, mcAlexon commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__close::before,
удалил

2023-06-11 20:35 UTC, GSemikozov requested changes

2023-06-11 20:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    padding: 16px;
паддинги тут лишние + не расстягиваем блок на всю ширину и высоту вьюпорта

2023-06-11 20:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    padding-bottom: 32px;
margin-bottom

2023-06-11 20:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__dark-mode{
переключалку темы в этой задаче не добавляем

2023-06-11 20:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger__open" id="burger-menu-open">
повторюсь, это не элемент блока бургер-меню, удалим класс burger__open

2023-06-11 20:35 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger__dark-mode{
и все что дальше с этим связано

2023-06-13 14:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-15 20:51 UTC, GSemikozov requested changes

2023-06-15 20:51 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__body{
выше описывали элементы блока .burger, а здесь вдруг переключились на .burger-menu?) если это отдельный блок с меню - то так его и надо оформить, как отдельный блок в папке components

2023-06-15 20:51 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +        <div class="burger__open" id="burger-menu-open">
все еще актуально

2023-06-16 17:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-21 10:47 UTC, GSemikozov approved these changes

2023-06-21 10:47 UTC, merged