Dz 3 accordeon
js-tasks-ru/htmlcss-20230411_pavlov-aleksandr pull request #6
Opened 2023-04-25 17:11 UTC by mcAlexon

2023-04-25 17:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-26 13:44 UTC, GSemikozov requested changes

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px; /*Нужно ли было тут задавать ширину аккордеона?*/
нет, это лишнее

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details summary::-webkit-details-marker {
если глобальные сбросы - то в normalize, если сбросы на уровне компонента - через классы

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 32px;
не по макету (и еще надо учитывать что паддинг снизу при .accordion__item[open] будет другой)

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 32px;
здесь же - не хватает стилей для оформления текста

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <summary class="name accordion__item">
лишний класс name

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion">
именно это - accordion__item, таких секций будет 3, все они будут завернуты в общий div с классом блока .accordion

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <summary class="name accordion__item">
и видимо это будет элемент блока accordion__summary

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <p class="content accordion__item">
а это accordion__text, прчием content здесь лишний

2023-04-26 13:44 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <p class="content accordion__item">
лишний элемент

2023-04-27 17:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-27 18:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-28 14:59 UTC, GSemikozov requested changes

2023-04-28 14:59 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-size: 16px;
не хватает стилей для описание текста (font-family, line-height, font-weight)

2023-04-28 14:59 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <p class="accordion__text">Accordion item 1 </p>
лишний элемент, здесь просто текст внутри summary

2023-04-28 14:59 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <p class="accordion__text2"> Текст который виден всем</p>
а этот текст - должен быть снаружи summary (класс будет accordion__text)

2023-04-29 12:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-29 12:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-29 17:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-01 12:12 UTC, GSemikozov requested changes

2023-05-01 12:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-family:'Inter';
и для accordion__summary тоже надо добавить

2023-05-01 12:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__text2{
это лишнее, удалим

2023-05-01 13:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 13:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-01 14:54 UTC, GSemikozov requested changes

2023-05-01 14:54 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary[open]{
так не надо)) и неправильно. Должно быть так: `.accordion__item[open] { padding-bottom: 32px; }`

2023-05-01 14:54 UTC, GSemikozov commented on assets/css/main.css
> +@import '../03-lection1/02-accordion/accordino.css';
буква `n` в конце названия файла думаю пригодится ;)

2023-05-02 14:10 UTC, GSemikozov requested changes

2023-05-03 13:51 UTC, GSemikozov approved these changes

2023-05-03 13:52 UTC, merged