Dz 4 hisogramm
js-tasks-ru/htmlcss-20230411_pavlov-aleksandr pull request #7
Opened 2023-05-01 16:33 UTC by mcAlexon

2023-05-01 16:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 16:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-01 16:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-02 14:12 UTC, GSemikozov requested changes

2023-05-02 14:12 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
лишнее

2023-05-02 14:12 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0;
по умолчанию и так 0

2023-05-02 14:12 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.text_element_number{
.histogram__number?

2023-05-02 14:12 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.text_element_number{
в общем ниже везде надо исправить именования классов по БЭМ )

2023-05-02 14:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-02 19:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-03 13:55 UTC, GSemikozov requested changes

2023-05-03 13:55 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 24px;
все еще актуально

2023-05-03 13:55 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.stats{
отдельный блок .stats внутри .histogram? или все-таки это элемент блока .histogram?

2023-05-05 13:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-06 10:53 UTC, GSemikozov requested changes

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border: 1px solid black;
цвет не по макету)

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-orders{
блок у нас .histogram, а не .histogram-orders, здесь речь идет об элементе блока, поэтому - .histogram__orders

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram-orders__number{
.histogram__numbers

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-bottom: 40px;
margin-bottom: 39px

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.Total{
.histogram__title

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: flex;
нет необходимости здесь задавать flex

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее. Вместо этого - align-items: flex-end

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-wrap: wrap-reverse;
и это лишнее

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.stats{
это все еще актуально

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.stats{
это элемент блока .histogram__column, border здесь не нужен

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_stats-el__1{
а модификаторы будут - .histogram__column_100 и тд

2023-05-06 10:53 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <a class="histogram-orders__total" href="vk.com">View all</a>
.histogram__link

2023-05-11 14:05 UTC, GSemikozov requested changes

2023-05-11 14:05 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border: 1px solid black;
все еще актуально

2023-05-11 14:05 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__orders__total{
.histogram__total

2023-05-12 14:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: flex;
display: flex; не нужен здесь

2023-05-12 14:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0 -5px;
можно удалить, марджины здесь не нужны

2023-05-16 06:29 UTC, GSemikozov requested changes

2023-05-16 06:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0 1px;
0 1px 0 0

2023-05-17 15:38 UTC, GSemikozov approved these changes

2023-05-17 15:38 UTC, merged